### ISSUE TITLE
Need Status Code as part of exception message

### ISSUE THREAD

**Issue by santhosh250595** [kawansoft/AceQL.Client2#12]
Hello Nicolas,

Hope you are doing well and keeping your health good.

We have a response from our Api with Status Code as 503 and some custom message.

With AceQl I'm not able to retrieve any status code and content. 

Is there any way from your side to append the status code and content with default aceql exception message.

Thanks in advance.

**Comment by ndepomereu** [comment]
Hi Santhosh,

Could you please be more specific? I don't understand "our Api"? Whats is it?
Please describe with a code sample, if possible?

**Comment by santhosh250595** [comment]
Hello Nicolas 

Below is the response from our curl call, For this call through AceQL client is giving exception message as "Exception of type 'AceQL.Client.Api.AceQLException' was thrown." 

< HTTP/1.1 503 Service Unavailable
< Date: Mon, 28 Jun 2021 05:55:31 GMT
< Content-Type: application/json
< Content-Length: 133
< x-amzn-RequestId: _____
< x-amz-apigw-id: _____
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
<
{ [5 bytes data]
100   133  100   133    0     0     50      0  0:00:02  0:00:02 --:--:--    50 { "message" : "Sorry for the inconvenience but we are performing some maintenance at the moment. We will be back online shortly!" }

**Comment by ndepomereu** [comment]
Hi Santhosh,
I don't understand. Please explain what your CURL is doing and how it's connected to AceQL. Please give clear details of the architecture.

**Comment by santhosh250595** [comment]
Hi,
We have AceQL server running in an AWS EC2 instance and an API GW is in place. During any maintenance activities Api GW would not allow requests to AceQL server instead it would return this particular message with status code 503.

**Comment by ndepomereu** [comment]
Hi Santhosh,
Please send source code of what exists today, and also source code of what you would like implemented in AceQL.

**Comment by santhosh250595** [comment]
Hello Nicolas,

Is there a way to add Content-type to header of http-client using AceqlConnection object.

I tried adding **connection.AddRequestHeader("Content-Type", "application/json");** but it doesn't recognize as a proper header.

**Comment by ndepomereu** [comment]
Hi Santhosh,
No, this is not possible because of C# HttpClient implementation. 
See this [StackOverflow question](https://stackoverflow.com/questions/10679214/how-do-you-set-the-content-type-header-for-an-httpclient-request)

Could you please explain what is your purpose, as we can then decide what is best to do in AceQL?

**Comment by santhosh250595** [comment]
Hello Nicolas,

We have AceQL server hosted in an AWS EC2 instance. If any update(s) needed in instance/server we give a custom response back from Api Gateway.  

The existing httpclient doesn't have any issue in getting the response if it is a GET request but when we are establishing the connection for first time it is making POST request with some content/data (Client Version and password) the response is not correct because the request is expecting Content-Type of the data.

When I added this piece of code to see the behaviour in AceQL client the response was fine.
HttpContent content = new FormUrlEncodedContent(postData);
content.Headers.ContentType = new MediaTypeWithQualityHeaderValue("application/json");

**Comment by ndepomereu** [comment]
Hi Santhosh,
Thanks, but this needs clarification in live mode.
Please send me email at contact@kawansoft so that we plan a Slack or Skype session.

**Comment by santhosh250595** [comment]
Hi Nicolas,

Thanks for the clarification plan but after adding the url encoded content type to mapping template in Api GW the issue is resolved and I'm able to get the response back.

Thanks for all.
