### ISSUE TITLE
GZip Result Property is read only XML Comment says default is true but false is default

### ISSUE THREAD

**Issue by santhosh250595** [kawansoft/AceQL.Client2#13]
Hello Nicolas,

Earlier versions of AceQl allowed setting value to GZip  but with latest version after introduction of ConnectionInfo class GZip property is set to readonly and also the comment mentions default value is true but its default value is false.

For now we are able to set the GZip value using ConnectionString property and its decoded to true.

In future, What will be the ideal way to set the value to GZip?

Thanks in Advance

**Comment by ndepomereu** [comment]
Hi Santhosh,
You are right: this is a documentation bug. `gzipResult `defaults to false in fact.

We favor objects' immutability in  C# AceQL, this is good practice. This is why there is no more setter for `gzipResult`.
The value must be defined in the connection string, as you did. It will be kept like this in the future.

As it is planned to release a new version in the next few days, C# comments will be fixed then, and user doc precision added.

**Comment by santhosh250595** [comment]
Hi, Thanks for the info.

**Comment by santhosh250595** [comment]
The AceQLConnection.RequestRetry property allows forcing a retry if a 
  SELECT query failed. If the failure was due to a GZIP issue, the failed 
  request is retried without any compression. This is experimental and
  AceQLConnection.RequestRetry default value is false.

Will this be valid?

**Comment by ndepomereu** [comment]
Yes, what you write is the correct explanation, but `AceQLConnection.RequestRetry `default value is true.

**Comment by santhosh250595** [comment]
Got it Thanks :)
