### ISSUE TITLE
System.NullReferenceException connection.OpenAsync() xamarin.forms

### ISSUE THREAD

**Issue by WillyBilly90** [kawansoft/AceQL.Client2#14]
Hi,

I use the AceQL.Client in a WPF app without errors, but when I use the same code to create a connection in Xamarin.Forms, then _System.NullReferenceException: 'Object reference not set to an instance of an object.'_ pops up when _await connection.OpenAsync()_ is called.

When I look in the debug info, it says that the error comes from:
_'connection.aceQLHttpApi.HttpStatusCode' threw an exception of type 'System.TypeInitializationException'_

The inner exception is: _{"Access to the path 'C:\\Users' is denied."}	System.Exception {System.UnauthorizedAccessException}_

That Xamarin.Forms, tested with UWP, can not write to C:\\Users is correct, but why should it write to that location ?

Does someone know how to get AceQL.Client2 work with Xamarin.Forms ?

**Comment by ndepomereu** [comment]
Hi,
It's a small design error in AceQL.Client2: there is a  debug/trace option, but even if the trace is never asked, a trace folder is always created at `OpenAsync()` call:
`C:\Users\<windows user>\AppData\Roaming\.aceql`

I will create a new version asap this week, meanwhile, may you can externally pre-create the folder before the AceQL Connection?

**Comment by WillyBilly90** [comment]
Hi, 

`C:\Users\<windows user>\AppData\Roaming\.aceql` allready exists, maybe created by my wpf version of the app.
I will wait for your new version and hopefully the error disappears.

**Comment by ndepomereu** [comment]
To be sure for the fix: Read access to the path is also forbidden by Xamarin ?

**Comment by WillyBilly90** [comment]
That is correct, Xamarin and UWP do not allow access to the userfolder.
Maybe you can use the temp folder ?

**Comment by ndepomereu** [comment]
Yes, I wll use temp folder with code:
`string folderPath = System.IO.Path.GetTempPath() + ".aceql";`

Please confirm there will be no Xamarin and UWP security issues?

**Comment by WillyBilly90** [comment]
That should work !

**Comment by ndepomereu** [comment]
Version 7.1 is online on NuGet and uses now temp folder `string folderPath = System.IO.Path.GetTempPath() + ".aceql";`

**Comment by WillyBilly90** [comment]
The inner exception is: {"Access to the path 'C:\Users' is denied."} System.Exception {System.UnauthorizedAccessException} is gone!
But still get an System.NullException. Can't find what is going wrong here.


```

using AceQL.Client.Api;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace WCCashApp.DbConnections
{
    public static class Customers
    {
        private static AceQLConnection conn=null;
        public static async Task<List<Klant>> GetCustomers(string SearchTerm)
        {
            try
            {
                ConnectionBuilder connectionBuilder = new ConnectionBuilder();
                conn = connectionBuilder.GetConnection();
                await conn.OpenAsync();
                // SQL stuff.
            }
            finally
            {
                await conn.CloseAsync();        
            }
            return customers;
        }
    }
}








using System.Linq;
using AceQL.Client.Api;



public class ConnectionBuilder
{
    private string server;
    private string database;
    private string username;
    private char[] password;

    public ConnectionBuilder()
    {
        this.server= WCCashApp.Properties.Resources.AceQlServerUrl;
        this.username= WCCashApp.Properties.Resources.AceQlUserName;
        this.database= WCCashApp.Properties.Resources.AceQlDatabaseName;
        this.password= WCCashApp.Properties.Resources.AceQlUserPassword.ToArray();
    }

    public AceQLConnection GetConnection()
    {
        string connectionString = $"Server={server}; Database={database};";
        AceQLConnection connection = new AceQLConnection(connectionString)
        {
            Credential = new AceQLCredential(username, password)
        };
        return connection;
    }
}
```

**Comment by ndepomereu** [comment]
Whats is the stack trace? Where is the  System.NullException?

**Comment by WillyBilly90** [comment]
System.NullException is raised here: `await conn.OpenAsync();`

This is the Call stack when the exception is raised:

```
> 	AceQL.Client.dll!AceQL.Client.Api.Http.AceQLHttpApi.HttpStatusCode.get()	Unknown
 	AceQL.Client.dll!AceQL.Client.Api.Http.AceQLHttpApi.OpenAsync()	Unknown
 	AceQL.Client.dll!AceQL.Client.Api.AceQLConnection.OpenAsync()	Unknown
>	WCCashApp.dll!WCCashApp.DbConnections.Customers.GetCustomers(string SearchTerm) Line 18	C#
 	WCCashApp.dll!WCCashApp.CustomersMainpage.FillCustomerList() Line 64	C#
 	WCCashApp.dll!WCCashApp.CustomersMainpage.StartSearchBtn_Click(object sender, System.EventArgs e) Line 53	C#
 	Xamarin.Forms.Core.dll!Xamarin.Forms.Button.Xamarin.Forms.Internals.IButtonElement.PropagateUpClicked()	Unknown
 	Xamarin.Forms.Core.dll!Xamarin.Forms.ButtonElement.ElementClicked(Xamarin.Forms.VisualElement visualElement, Xamarin.Forms.Internals.IButtonElement ButtonElementManager)	Unknown
 	Xamarin.Forms.Core.dll!Xamarin.Forms.Button.SendClicked()	Unknown
 	Xamarin.Forms.Platform.UAP.dll!Xamarin.Forms.Platform.UWP.ButtonRenderer.OnButtonClick(object sender, Windows.UI.Xaml.RoutedEventArgs e)	Unknown

```

**Comment by ndepomereu** [comment]
It seems the HttpClient refuses to execute. 
I will provide asap some debug tests to do.

**Comment by WillyBilly90** [comment]
Found it!

When initialize an instance of HttpManager   WebProxy GetWebProxy() is called.

There is this piece of code:
```
// Test the secret URL, if it is bypassed, there is no Default/System proxy set, so we will return null:

if (webProxy.IsBypassed(new Uri(HttpClientHandlerBuilderNew.SECRET_URL))) {
             return null;
             }
            else
            {
              return webProxy;
            
            }
```

I commented it out and return null, now it works.
It looks like `if (webProxy.IsBypassed(new Uri(HttpClientHandlerBuilderNew.SECRET_URL)))` is calling httpManager, but it is not initiated, so a NullReferenceExeption occurs.
For me it works now, but I think more people should have problems using it with Xamarin.Forms

**Comment by ndepomereu** [comment]
Hi WillyBily,

Thanks a lot for the diagnosis! 

Yes, `webProxy.IsBypassed(new Uri(HttpClientHandlerBuilderNew.SECRET_URL)))` can trigger a `NullReferenceException`.
We are working on it by retesting all on Xamarin...
And we will make a new version tomorrow.

**Comment by ndepomereu** [comment]
The New 7.2 version which fixes the `NullReferenceException`  on ` if (webProxy.IsBypassed(new Uri(HttpClientHandlerBuilderNew.SECRET_URL)))` in `DefaultWebProxyCreator` class is published.
